name: Deploy to GH Pages
on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  Deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh_pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_MOVIESTILLS }}
